src/BundlerMinifier/Minify/HtmlOptions.cs
src/BundlerMinifierVsix/JSON/bundleconfig-schema.json

Add `CustomAngularDirectiveList` and `ProcessableScriptTypeList` properties to HTML options.

Add additional properties to HTML options

---

src/BundlerMinifier/Bundle/BundleFileProcessor.cs

This is to make changes to files of a folder bundle Input source to cause a bundle update.
Currently i have to save the bundle(via the context menu), since i don´t use the "MSBuild Support"
I actually think Recursive file globing should be supported as, but right now this fix is for the current top-diretory globbing support.
```javascript
[
{
"outputFileName": "www/index.html",
"inputFiles": [
"app/_index_begin.html",
"app/_index.html",
"app/core/directives/login/",            //---|
"app/core/directives/userprofile/",           |
"app/core/directives/userphoto/",             | recursive globbing would make this easier. 
"app/core/directives/currentuser-name/",//---|
/*...*/
"app/_index_end.html"
]
}
] 
```

Support Folder Bundle Update On Save

---

src/BundlerMinifier/Bundle/BundleFileProcessor.cs

Currently when the path specified for "outputFileName" doesn´t exists the BundlerMinifier fail
with an incorrect(actually more unhelpful than incorrect) message about the possibility of a format error....
I really think specifying an output path "a/b/c/d.html" should work even if "a/" doesn´t exists.

Allow Creation Of Output Dirs When Not Exists

---

src/BundlerMinifier/MSBuild/BundlerBuildTask.cs

I found that on my build server for CI the min file was not being written to because the readonly flag was not first being removed from the file.

Removing readonly flag before writing to min file

---

src/BundlerMinifier/Program.cs

If no argument is supplied from the command line, show info about usage
and exit program.

Fixed crash in CLI when no argument is supplied

---

src/BundlerMinifier/Bundle/BundleFileProcessor.cs
src/BundlerMinifier/BundlerMinifier.csproj
src/BundlerMinifier/MSBuild/BuildBundlerMinifier.targets
src/BundlerMinifier/MSBuild/BundlerCleanTask.cs

Remove all output files when Build>Clean or Build>Rebuild run.

MSBuild BundlerCleanTask

---

src/BundlerMinifier/Bundle/BundleHandler.cs

Partially resolves issue https://github.com/madskristensen/BundlerMinifier/issues/77. It will overwrite bundle configurations for existing bundles pointing to the same output location. 
This overwrite would've happened anyway when the configuration file was processed, as it would have overwritten the original bundle's output file contents when processing the new entry.
This could/should be enhanced to provide a dialog box with options to merge/overwrite the existing bundle.

Created bundles overwrite existing bundles with same output path

---

src/BundlerMinifier/BundlerMinifier.csproj
src/BundlerMinifier/Minify/HtmlOptions.cs
src/BundlerMinifier/packages.config
src/BundlerMinifierVsix/JSON/bundleconfig-schema.json

This property allows to preserve case of tag and attribute names during HTML minification (useful for Angular 2 templates).

Add `PreserveCase` property to HTML options

---

src/BundlerMinifierVsix/Resources/Files/gulpfile.js

There's a missing semicolon in the gulp `clean` task.

Add missing semicolon in gulp clean task

---

README.md

This PR addresses a couple minor spelling mistakes in the `README.md` file.

Fix some minor spelling mistakes in README

---

src/BundlerMinifierVsix/Resources/Files/package.json

This PR explicitly defines the **private** property in `package.json` and sets it to `true`. This makes the `package.json` file consistent with the **npm Configuration File** item template.

Make package.json consistent with item template

---

src/BundlerMinifierVsix/BundlerMinifierVsix.csproj
src/BundlerMinifierVsix/Commands/ConvertToGulp.cs
src/BundlerMinifierVsix/Resources/Files/gulpfile.js
src/BundlerMinifierVsix/packages.config

This PR addresses issue #161 by stripping comments from the `bundleconfig.json` file before creating `gulpfile.js`. This eliminates the need to manually remove the comments.

Strip comments in bundleconfig.json during Gulp conversion

---

src/BundlerMinifierVsix/Resources/Files/gulpfile.js
src/BundlerMinifierVsix/Resources/Files/package.json

Change the encoding of `gulpfile.js` and `package.json` from **Western European (Windows)** to **Unicode (UTF-8) with signature**. This makes the files consistent with the encoding used in the VS "Gulp Configuration File" and "npm Configuration File" item templates.

Modify gulpfile.js and package.json file encoding types

---

src/BundlerMinifier.Core/Program.cs

fix typo in help message

---

src/BundlerMinifierVsix/Resources/Text.Designer.cs
src/BundlerMinifierVsix/Resources/Text.resx

Change "ininstall" to "uninstall" for the `NugetErrorUninstalling` value in `Text.resx`.

Fix spelling mistake in resx file

---

src/BundlerMinifierVsix/Resources/Files/gulpfile.js

This PR addresses the concerns expressed in issue #194. A couple other things to note about this PR:
- Using regular expression literals instead of the `RegExp` object to improve performance, as per the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)
- The `outputFileName` property in `bundleconfig.json` is restricted to `.html` or `.htm` extensions. The `gulpfile.js` was only searching for `.html` extensions. I've adjusted `gulpfile.js` to match the same regex being enforced in the JSON schema [here](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/bundleconfig.json#L94).

Use regex literals instead of RegExp object

---

src/BundlerMinifier/BundlerMinifier.csproj

Quoted the build event path for Nuget.exe in the post build event for when MSBuildProjectDirectory contains spaces in the directory path

Fix for Issue #207

---

src/BundlerMinifierTest/BundlerMinifierTest.csproj

The `test3.json` file, used in the `JustGzip` unit test, wasn't included in the project. This PR explicitly includes the file in the project to make it clear that it's being used.

Include test3.json file in BundlerMinifierTest project

---

src/BundlerMinifierTest/artifacts/test1.json

The `test1.json` file's HTML minification section references a `whitespaceMinificationMode` property which no longer exists.

Remove old whitespaceMinificationMode property from test1.json

---

CHANGELOG.md
src/BundlerMinifier.Core/project.json
src/BundlerMinifier.Core/project.lock.json
src/BundlerMinifier/BundlerMinifier.csproj
src/BundlerMinifier/packages.config
src/BundlerMinifierTest/BundlerMinifierTest.csproj
src/BundlerMinifierTest/BundlerTest.cs
src/BundlerMinifierTest/artifacts/file3.html
src/BundlerMinifierTest/artifacts/file3.js
src/BundlerMinifierTest/artifacts/test4.json
src/BundlerMinifierTest/artifacts/test5.json

Upgrade the [NUglify](https://www.nuget.org/packages/NUglify/) NuGet package from version 1.5.1 to version 1.5.2 to address issues https://github.com/madskristensen/BundlerMinifier/issues/135 and https://github.com/madskristensen/BundlerMinifier/issues/63. Also added a couple unit tests specifically for the 2 aforementioned issues.

Upgrade NUglify NuGet package to v1.5.2

---

CHANGELOG.md
src/BundlerMinifier.Core/Minify/HtmlOptions.cs
src/BundlerMinifier.Core/project.json
src/BundlerMinifier.Core/project.lock.json
src/BundlerMinifier/BundlerMinifier.csproj
src/BundlerMinifier/packages.config
src/BundlerMinifierTest/BundlerMinifierTest.csproj
src/BundlerMinifierTest/BundlerTest.cs
src/BundlerMinifierTest/artifacts/file4.html
src/BundlerMinifierTest/artifacts/test6.json

Address issue #199 by upgrading to the NUglify v1.5.4 NuGet package. This gives us support for the `KeepOneSpaceWhenCollapsing` property when doing HTML minification.

Add support for NUglify property KeepOneSpaceWhenCollapsing

---

src/BundlerMinifier.Core/Bundle/Bundle.cs

Fixed console message that should be shown only if there is a setting and there are no files by pattern.

No files matched the pattern even if there are matched files

---

src/BundlerMinifier/build/BuildBundlerMinifier.targets

I have updated the `BuildMinify` target to run after the TypeScript compilation is finished. It has no effect if TypeScript is not used in the project. I have also tested compatibility with WebCompiler. Didn't find any issues.
This PR replaces the https://github.com/madskristensen/BundlerMinifier/pull/168 pull request.

BundleMinify runs after TypeScript is compiled

---

src/BundlerMinifier.Core/Minify/BundleMinifier.cs

Minification fails if the target directory does not exist. This fix will create the directory before writing the file. Note `Directory.CreateDirectory` does nothing if the directory already exists.

Create directory if it does not exist

---

BundlerMinifier.sln
src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
src/BundlerMinifier.TagHelpers/Bundle.cs
src/BundlerMinifier.TagHelpers/BundleExtensions.cs
src/BundlerMinifier.TagHelpers/BundleOptions.cs
src/BundlerMinifier.TagHelpers/BundleTagHelper.cs
src/BundlerMinifier.TagHelpers/BundlerMinifier.TagHelpers.csproj
src/BundlerMinifier.TagHelpers/BundlesProvider.cs
src/BundlerMinifier.TagHelpers/IBundleProvider.cs

This PR add a TagHelper to use bundles declared in the `bundleconfig.json` file.
````html
<bundle name="wwwroot/css/bundle.min.css" />
<bundle name="wwwroot/js/bundle.min.js" />
````
In development environment it expands the bundle to all files, so you can easily debug your code.
In production environment it uses the bundle file.
Issues:
- #137 Add TagHelper support
- https://github.com/meziantou/Meziantou.AspNetCore.BundleTagHelpers/issues/3

WIP: Add TagHelper

---

README.md

Remove specific Visual Studio version number (2015) from Extensibility Tools hyperlink in ReadMe file

Remove version no. from ReadMe Ext.Tools hyperlink

---

src/BundlerMinifier.Core/Minify/CssRelativePathAdjuster.cs

In ASP.NET controls, css may contain embedded resources references, invalid characters exception that throws if it exists.
The embedded resources references like this:
.aspnet {
background: url('**<%=WebResource("Namespace.Class.image.png")%>**');
}
So I added **<** in the **_rxUrl** to exclude.

exclude embedded resource references

---

src/BundlerMinifier.TagHelpers/BundleTagHelper.cs
src/BundlerMinifier.TagHelpers/BundlesProvider.cs

This changes fixes the error described in issue 418. Added a new constructor with IHostingEnvironment parameter which helps to resolve the path for bundleconfig.json
https://github.com/madskristensen/BundlerMinifier/issues/418

Fix for "Unable to load bundles" while running using IIS Express

---

src/BundlerMinifier.Core/Bundle/Bundle.cs
src/BundlerMinifier.Core/Bundle/BundleFileProcessor.cs
src/BundlerMinifier.Core/Bundle/BundleHandler.cs
src/BundlerMinifier.Core/Minify/BundleMinifier.cs

BundlerMinifier is adding 6 sec to our build time, even if no file have changed.
If a CS file is changed in our project and we rebuild, BundleMinifier is accounting for 30% of the build time.
This is a significant hurdle on the code/debug feedback loop in our project.
This PR skip minification if all the inputs are older than the existing minified file.

Skip bundle minifying if all the inputs are older than the minified file

---

appveyor.yml
src/BundlerMinifier.TagHelpers/BundleExtensions.cs
src/BundlerMinifier.TagHelpers/BundleOptions.cs
src/BundlerMinifier.TagHelpers/BundleTagHelper.cs
src/BundlerMinifier.TagHelpers/BundlerMinifier.TagHelpers.csproj
src/BundlerMinifier.TagHelpers/BundlesProvider.cs
src/BundlerMinifier.TagHelpers/Shims.cs

The bundle tag helper does not work on netcoreapp3.0 despite BundlerMinifier targetting netstandard20 which is supported by netcoreapp3.0.
Long story short, netstandard2.0 is using `ITagHelper` from `Microsoft.AspNetCore.Razor.Runtime` while netcoreapp3.0 is using `Microsoft.AspNetCore.Razor`.
However, `Microsoft.AspNetCore.Razor` is  no longer produced, it is now an integral part of the netcoreapp3.0 runtime. (You can see that the package has no 3.0 version on https://www.nuget.org/packages/Microsoft.AspNetCore.Razor/)
This is documented on this document, https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references 
Also, we now use  `IWebHostEnvironment` instead of `IHostingEnvironment` to prevent this error on …

Add .netcoreapp3.0 support for the BundleTagHelper

---

src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
src/BundlerMinifier/BundlerMinifier.csproj

Add `netcoreapp3.0` as a supported target framework.
Relates to #442.

Support .NET Core 3.0 in global tool

---

appveyor.yml
src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
src/BundlerMinifier.TagHelpers/BundlerMinifier.TagHelpers.csproj
src/BundlerMinifier/BundlerMinifier.csproj

Adds netcoreapp3.1 as a supported target framework.
Relates to #460.

Add .NET Core 3.1 support

---

src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
src/BundlerMinifier.TagHelpers/BundlerMinifier.TagHelpers.csproj
src/BundlerMinifier/BundlerMinifier.csproj

CSProj files have been updated to enable SourceLink in your nuget
---
*[This pull request was created with an automated workflow]*
I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.
**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)
You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx
If you are interesting about this automated workflow …

[PR] The proj files have been updated to enable SourceLink

---

src/BundlerMinifier.TagHelpers/BundlesProvider.cs

Spent some time diagnosing issue in release package as bundleconfig.json wasnt tagged as "Content" "copy if newer" so not present in release folder, thought message could be improved slightly to help debug on hosting server environment.

Elaborate on Error message when bundle path is not present

---

src/BundlerMinifierVsix/Commands/ProjectEventCommand.cs

This fix avoids starting another callback until the current one has finished to avoid thread pool starvation.
We've automatically captured dumps where overlapping timers are all blocked on the same thread:
```
ntdll.dll!_ZwWaitForMultipleObjects@20() Line 825 Unknown
KERNELBASE.dll!WaitForMultipleObjectsEx(unsigned long nCount, void * const * lpHandles, int bWaitAll, unsigned long dwMilliseconds, int bAlertable) Line 1551 C
[Managed to Native Transition]
mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<EnvDTE.Project, System.IO.FileSystemWatcher>.AcquireLocks(int fromInclusive, int toExclusive, ref int locksAcquired) Unknown
mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<EnvDTE.Project, System.IO.FileSystemWatcher>.AcquireAllLocks(ref int locksAcquired) …
```

Avoid overlapping timers to avoid threadpool starvation
